### ISSUE TITLE
Add options for mpv

### ISSUE THREAD

**Issue by fliegentoeter** [grmat/play-with#6] opened 2018-10-13 18:39 UTC
Is there a way to send some options for mpv when opening videos?
I would like to set some quality/cache options like:

```
 --ytdl-format=45/22/bestvideo[height<=720]+bestaudio/bestvideo[height<=720] \
 --ytdl-raw-options=geo-bypass=,ignore-errors=,continue= \
 --title="$TITLE" \
 --cache=auto \
 --cache-default=100000 \
 --autofit-larger=100%x100% \
 --autofit-smaller=100%x100% \
 --geometry=50%:50% \
 --demuxer-thread=yes \
 --demuxer-readahead-secs=60 \
 --cache-secs=60 \
 --cache-initial=1024
```

**Comment by grmat** [comment] 2018-10-14 11:59
Hi,
as play-with is deliberately doing nothing but handing the URL to the preferred program (in that case mpv), that's not possible. Technically, play-with doesn't call mpv itself, so it can't set additional options to the call. Firefox downloads the playlist file provided by play-with and then lets mpv open it. That's intentional as that doesn't require a native-messaging client, and the sole reason play-with exists. There are other addons that rely on native-messaging and can fulfil your needs.

The way I use it is to add a new profile in the mpv config, set the desired options there and select it as the new default profile, so its options will be used when mpv gets called by Firefox (or anything else without additional arguments). When opening mpv from a terminal, I can still select another profile. Further convenience possibilities are using shell aliases or creating an additional .desktop entry containing the desired profile.

closing, as duplicate of #4

**Closed as completed** 2018-10-14 12:09 UTC
Labels: duplicate
