### ISSUE TITLE
Issues on Windows

### ISSUE THREAD

**Issue by ghost** [grmat/play-with#1] opened 2018-05-13 02:57 UTC
I'm having trouble getting the add-on to work on Windows 10; I'm using mpv 0.28.0-564-g11289d5238 with latest youtube-dl in the mpv folder. Also using Nightly 62.

If I click the toolbar button on any YouTube video page, I get the following prompt.
![firefox_2018-05-12_19-53-41](https://user-images.githubusercontent.com/32758295/39963379-77ebc122-561e-11e8-9468-cca5d4725a39.png)

But upon clicking OK, Firefox only downloads a small file containing the following lines.
```
#EXTM3U
https://www.youtube.com/watch?v=gCcx85zbxz4
```

Am I doing something wrong? Or is that an issue with FF/Extension?

**Comment by grmat** [comment] 2018-05-13 11:16
From your description, the addon does exactly what it is intended and expected to do.

Have you tried opening the file with mpv? You can also try opening from a terminal (`mpv [filename]`) to see the output of mpv in case something goes wrong.

I'm closing this issue because the Addon is working, but feel free to comment if you require further assistance.

**Comment by KotKod** [comment] 2018-05-28 15:23
Hi @grmat 
I have same issue as @tp78903. 
Please correct me if  i I am wrong but i expected that when i will use toolbar button then mpv player will open link automatically without the need for manual opening mpv player and opening file manually. How this plugin helps? Instead of plugin usage I can just run mpv player and provide instead of downloaded file the direct web path. This is even simpler. I am a little bit  confused.

**Comment by grmat** [comment] 2018-05-28 15:40
Hi

> Please correct me if i I am wrong but i expected that when i will use toolbar button then mpv player will open link automatically

That's *not* what it's intended to do and I think that its behaviour is pretty well documented.

> the need for manual opening mpv player and opening file manually. How this plugin helps? Instead of plugin usage I can just run mpv player and provide instead of downloaded file the direct web path. This is even simpler.

There is no need for manual opening. Firefox asks to open the generated playlist file with mpv, you can say yes and even tick the checkbox and tell firefox to do this all the time, so there won't be the need for two clicks in the future.

It's not simpler for me to copy the url of the current page or an embedded video, open mpv and paste it there manually. If it is for you, you are free to use an extension that requires a native messaging client or no extension at all.

I won't change this extension to use a native messaging client, as offering an alternative without is the sole reason this extension even exists.

**Comment by KotKod** [comment] 2018-05-28 18:56
@grmat Thank you a lot for fast answer.  
Refering to below part of your feedback? 
>There is no need for manual opening. Firefox asks to open the generated playlist file with mpv, you can say yes and even tick the checkbox and tell firefox to do this 

I do not know if I explained this clearly before but in my case (and in @tp78903 I believe too) the plugin is only downloading the plain text file with the M3U header, nothing more. Even if option Open with (chosen player) is set. 
For example I have in firefox in options for content type **mailto** set to use my mail client so when I am clicking such content then my mail client is starting. Or because I have set to open with my torrent client content type **magnet** so when i click such link then its opening. 
Therefore I expected that after selecting in pop op window "Open with: mpv" with check box "Do this automatically..."  then every time plugin will generate plain text file and mpv will open this file automatically. I cross checked firefox options and I have set currently content type **video/x-mpegurl** to be opened with mpv player. But as I mentioned, plugin is only generate file, firefox is downloading this file to temp directory and nothing else happens.

**Comment by grmat** [comment] 2018-05-28 22:30
Thanks for the elaboration. That's in fact not how it is supposed to work. I don't have Windows on this machine, but will check later.

In the meantime, could you try opening the downloaded file manually with mpv from the command line, so the output is visible in the console?

If we're lucky you're just affected by #3 in which case a config switch for mpv will resolve the issue for now.

**Comment by KotKod** [comment] 2018-05-29 19:49
Hi again,
This is screen from command line output during playing the generated playlist file:
![mpv_play](https://user-images.githubusercontent.com/25156101/40681171-b159228e-6388-11e8-88ef-30dbd81483ee.PNG)
I am also attaching generated playlist (i have zipped file as GitHub not allow me to attach direct file): 
[tBGfL31c.zip](https://github.com/grmat/play-with/files/2050442/tBGfL31c.zip)
BTW: Maybe for Windows the problem is caused that generated file do not have m3u playlist extension when for UNIX machines this can be irrelevant? 

I also added to mpv configuration `load-unsafe-playlists=yes` flag but this did not improve the functionality of the plugin. As mpv can play without any problems the generated plain text files maybe it's related with some browser settings? Unfortunately, I have no experience to debug this.

**Comment by grmat** [comment] 2018-05-29 20:40
Unfortunately, I'm still not able to reproduce the issue, even on Windows.

Can you tell me what versions of which programs you are using? I've just tried with FF 60.0.1, mpv 0.28.0 (built 2017-12-25, most recent listed [here](https://mpv.srsfckn.biz/)) and ytdl 2018.05.26 and it works flawlessly.

Your zip gave me the idea that mpv on windows would expect `\r\n` after the m3u header, but that assumption seems wrong, as it works for me and also for you if you open the file manually. For the file extension, I don't think it makes a difference, as the MIME type is set and Firefox does allow to chose mpv for that. And I think opening the file e.g. from Windows Explorer works for you as well?

Could you test again with the browser console opened (Ctrl+Shift+J) and see if it prints any helpful info at the time of failure? You can click the trash bin to clear the previous output prior to triggering the addon. Also, please check for the file type default program in Windows, not only in FF.

**Comment by magictucura** [comment] 2018-05-29 23:29
I could reproduce this issue.
Specs:
Windows 7
FF 66.0.1
mpv 0.28.0
ytdl 2018.05.26

The console logs the following exception:

```
"play-with attempting to play url https://www.twitch.tv/summit1g"  background.js:10:3
[Exception... "Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsIAnnotationService.setPageAnnotation]"  nsresult: "0x80070057 (NS_ERROR_ILLEGAL_VALUE)"  location: "JS frame :: resource://gre/modules/DownloadHistory.jsm :: updateMetaData :: line 130"  data: no]  (unbekannt)
fileExtension is null```

Starting the file with mpv works fine.

**Comment by KotKod** [comment] 2018-05-30 07:02
I have similar exception in ff console as @Tucura 
My environment:
Windows 7
Firefox 60.0.1
mpv 0.28.0
youtube-dl 2018.05.26

```
"play-with attempting to play url https://www.youtube.com/watch?v=QwOU3bnuU0k"  background.js:10:3
[Exception... "Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsIAnnotationService.setPageAnnotation]"  nsresult: "0x80070057 (NS_ERROR_ILLEGAL_VALUE)"  location: "JS frame :: resource://gre/modules/DownloadHistory.jsm :: updateMetaData :: line 130"  data: no]  (unknown)
fileExtension is null
```

I also did check of default programs in windows setups ...

> Also, please check for the file type default program in Windows, not only in FF

...but in MS Windows the association a file type with a program is based extension and generated by plugin files are without extension so i think that currently  it is not possible to do association with them.

**Comment by grmat** [comment] 2018-05-30 11:57
Thanks for your feedback.

While I was still unable to reproduce the issue (Firefox somehow automatically appends `.m3u.m3u` to the file name on my Windows machine) I've set up a little test page on https://grmat.github.io/m3utest/. This mimics the way this extension works and there might be a workaround.

Could you please visit the page, and try the different options? At this point it doesn't even matter which URL you paste, the box just shouldn't be empty. You can also choose to open the file with notepad to see if FF manages to opens anything at all. Please make sure to force-reload the page in between tries with Ctrl+F5.

I don't think the crlf will have any effect, but who knows. If the workaround is successful, I'll include it into the extension, temporarily however, because I still want to figure out why it works on my Windows machine and not on yours. There's also the drawback that Firefox will show the popup window every time, even if you tick the box with this method, but I guess for now it's better than nothing.

**Comment by grmat** [comment] 2018-05-30 14:19
I was finally able to reproduce the issue on Windows.

The problem is that during early development/testing, the default behaviour was the one as in the above "workaround". This resulted in FF connecting the `.m3u` file ending to the MIME-type of the file, stored in `handlers.json` inside the FF profile. FF will then append the file extension to the file name and not run into the null exception.

I've submitted a bug report to Firefox because I think that's not what should happen. You can track the upstream bug report here: https://bugzilla.mozilla.org/show_bug.cgi?id=1465458

Now there are two options:
1. I set the "workaround" to be the default behaviour
   this has the advantage that everybody gets the fix and the disadvantage that nobody can use the "always open with mpv" checkbox anymore, and everyone has to accept the popup every time
1. I ask every Windows user to download a `.m3u` file once, so that Firefox can store the file extension/mime type connection. This has the advantage that users might miss this notice and not everyone gets it working, but the advantage that it doens't break the checkbox.

Any opinions?

**Comment by KotKod** [comment] 2018-05-30 16:36
Hi,
To not impact users of others system the solution 2. look to be more clear until bug solving from mozilla side. 

> I ask every Windows user to download a .m3u file once

Or option 3)  Maybe for Windows user You can prepare extra version with  "workaround"?
After usage first time this extra version then users can install default version because extension/mime type connection should be already present. Or you can add to default version some check bock to switch to workaround mode in case off issue for Windows machines?

**Comment by grmat** [comment] 2018-05-31 22:35
I've just pushed out an update. I've tested it on both "broken" and fresh profiles on Windows. Could you please also do a short test and report back? Here's how:

1. Do the update
1. Open a page and use play-with. The file will be named `streaming.m3u`. Tell Firefox to open it with mpv (you will have to, even if you previously told it should always open with mpv)
1. reload the current page, try again
1. Firefox will append `m3u.m3u` to the generated file name and succeed in opening the file in mpv
1. Please report back, whether it works as described or not.

**Comment by ghost** [comment] 2018-06-02 01:59
Works perfectly now; thanks:)

**Comment by grmat** [comment] 2018-06-02 15:14
Nice. Thanks for your feedback and have fun :wink:

**Closed as completed by grmat** 2018-06-02 15:14 UTC

**Comment by KotKod** [comment] 2018-06-03 21:36
> Works perfectly now; thanks:)

I can also confirm, problem solved :+1: 
Great job as this is only available for windows version with is working whiteout extra daemon.

PS. And some nice to have :-) Have you thought about adding the possibility of passing additional arguments for player?
